project:
  type: website
  output-dir: _site
  
date-modified: last-modified
date-format: long
    
website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: experience.qmd
        text: Experience
      - href: education.qmd
        text: Education
  sidebar:
    style: docked
    logo: images/bio-pic.jpg
    contents:
      - text: "Alec Bodolay"
      - text: "USC | CHLA"
        
      - text: "{{< ai google-scholar >}} &nbsp; &nbsp; Google Scholar"
        href: https://scholar.google.fr/citations?user=bodolayalec
        
      - text: "{{< ai researchgate >}} &nbsp; &nbsp; ResearchGate"
        href: https://www.researchgate.net/profile/Alec-Bodolay
        
      - icon: github
        text: "&nbsp;&nbsp;  GitHub"
        href: https://github.com/alecbodolay/
        
      - icon: linkedin
        text: "&nbsp;&nbsp;  LinkedIn"
        href: https://www.linkedin.com/in/alecbodolay/
        
      - text: '<i class="ai ai-orcid"></i>&nbsp; &nbsp; ORCID'
        href: https://orcid.org/0009-0006-9030-4711
        
      - text: "Contact:"
      - icon: envelope-fill
        text: "&nbsp;&nbsp; Email"
        href: "mailto:bodolay@usc.edu"
        
  page-footer: "Last Updated: {{< meta date-modified >}} <br/> Copyright © 2023 - 2026, Alec Bodolay. All rights reserved "


format:
  html:
    theme: [cosmo, custom.scss]
    css: styles.css
    toc: true
    fontawesome: true
    title-block-style: none
    grid:
      sidebar-width: 450px
      body-width: 800px;
      margin-width: 150px
 
editor: visual

