---
title: ""
---

## Conference

::: columns
::: {.column width="5%"}
\[1\]
:::

::: {.column width="95%"}
Costello, M., **Bodolay, A.**, Gray, C., Du, R., Potter, K., & Schuster, R. (2025). Emotional Reactivity is a Transdiagnostic Risk Factor for Substance Use Initiation in Middle and High School Students. *Drug and Alcohol Dependence*, 267, 111623 <br/> [\[abstract\]](https://www.sciencedirect.com/science/article/abs/pii/S0376871624005489)
:::
:::

::: columns
::: {.column width="5%"}
\[2\]
:::

::: {.column width="95%"}
Schuster, R., Cather, C., Pachas, G., Iroegbulem, V., Dufour, J. R., Casottana, K. D., Zhao, J., Potter, K., **Bodolay, A.**, Evins, A. E. (2025). Characteristics of Adolescents Presenting for a Pharmacotherapy Vaping Cessation Trial who Never Smoked Tobacco Regularly. *Drug and Alcohol Dependence*, 267, 111982 <br/> [\[abstract\]](https://www.sciencedirect.com/science/article/abs/pii/S0376871624009074)
:::
:::



## Journal

::: columns
::: {.column width="5%"}
\[1\]
:::

::: {.column width="95%"}
Costello M. A., Pascale M. P., Potter, K., Knoll, S. J., **Bodolay, A.**, Kaur J., Du, R., Greenspan, L., Gray, C. A., McIntyre, J., & [Schuster, R. M.](https://researchers.mgh.harvard.edu/profile/12192374/Randi-Schuster) (2025). Understanding Adolescent Mental Health Symptom Progression in School-Based Settings: The Substance Use and Risk Factors (SURF) Survey. *School Psychology* <br/> [\[paper\]](https://psycnet.apa.org/doiLanding?doi=10.1037%2Fspq0000681)
:::
:::

::: columns
::: {.column width="5%"}
\[2\]
:::

::: {.column width="95%"}
Pachas, G. N., Reeder, H. T., [Evins, A. E.](https://researchers.mgh.harvard.edu/profile/210699/Anne-Evins), Casottana, K., Borrego, M. M., **Bodolay, A.**, Gray, C. A., Potter, K., W., Keuroghlian, A. S., & [Schuster, R. M.](https://researchers.mgh.harvard.edu/profile/12192374/Randi-Schuster) (2025). Substance use, suicidal behaviors, and other mental health outcomes among youth with intersectional sexual and gender diverse identities. *Journal of the American Academy of Child & Adolescent Psychiatry Open*. In Press. <br/> [\[paper\]](https://www.jaacapopen.org/article/S2949-7329(25)00001-8/fulltext)
:::
:::

::: columns
::: {.column width="5%"}
\[3\]
:::

::: {.column width="95%"}
Liu, J., Knoll, S. J., Pascale, M. P., Gray, C. A., **Bodolay, A.**, Potter, K. W., Gilman, J., [Eden Evins, A.](https://researchers.mgh.harvard.edu/profile/210699/Anne-Evins), & [Schuster, R. M.](https://researchers.mgh.harvard.edu/profile/12192374/Randi-Schuster) (2024). Intention to quit or reduce e-cigarettes, cannabis,and their co-use among a school-based sample of adolescents. *Addictive Behaviors*, 157, 108101 <br/> [\[paper\]](https://pubmed.ncbi.nlm.nih.gov/38986353/)
:::
:::

::: columns
::: {.column width="5%"}
\[4\]
:::

::: {.column width="95%"}
Gray, C. A., Iroegbulem, V., Deming, B., Butler, R., Howell, D., Pascale, M. P., **Bodolay, A.**, Potter, K., Turncliff, A., Lynch, S., Whittaker, J., Ward, J., Maximus, D., Pachas, G. N., & [Schuster, R. M.](https://researchers.mgh.harvard.edu/profile/12192374/Randi-Schuster) (2023). Pragmatic Clinical Effectiveness Trial of a Novel Alternative to Punishment for School-Based Substance Use Infractions: Study Protocol for the iDECIDE Curriculum. *Frontiers in Public Health*, 11, 1203558 <br/>[\[paper\]](https://pubmed.ncbi.nlm.nih.gov/37670822/)
:::
:::
